# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170502_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth date'),
        ),
    ]
