# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelTable(
            name='dish',
            table=None,
        ),
    ]
