# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_calc', '0002_auto_20170318_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'FoodCategory',
                'verbose_name_plural': 'FoodCategories',
            },
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='FoodType',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='type',
            new_name='food_type',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(to='health_calc.Product'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='food_type',
            field=models.ManyToManyField(to='health_calc.FoodType'),
        ),
        migrations.AddField(
            model_name='dish',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_calc.FoodCategory'),
            preserve_default=False,
        ),
    ]
