# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:17
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_calc', '0003_auto_20170409_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food category', 'verbose_name_plural': 'Food categories'},
        ),
        migrations.AddField(
            model_name='dish',
            name='eating_time',
            field=bitfield.models.BitField((('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('after_lunch', 'After lunch'), ('dinner', 'Dinner')), default=None),
        ),
        migrations.AddField(
            model_name='dish',
            name='energyValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='serve_type',
            field=bitfield.models.BitField((('garnier', 'Garnier'), ('desert', 'Desert'), ('bad', 'BAD')), default=None),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='food_type',
        ),
        migrations.AddField(
            model_name='dish',
            name='food_type',
            field=models.ManyToManyField(to='health_calc.FoodType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energyValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='lipidsNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteinsNumber',
            field=models.IntegerField(default=0),
        ),
    ]
